import { TWMaterialComponents } from "@/lib/twMaterialAssets";
import "./globals.css";
import { AppHeader } from "@/components/primary/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <section className="">
          <TWMaterialComponents>
            <AppHeader />
            <section className="">{children}</section>
          </TWMaterialComponents>
        </section>
      </body>
    </html>
  );
}
